version: '2'
services:
  opensips-rec:
    image: qxip/docker-hepswitch:hep
    privileged: true
    environment:
      ADVERTISED_RANGE_FIRST: 20000
      ADVERTISED_RANGE_LAST: 20100
    volumes:
       - /var/lib/mysql
    ports:
      - "9060:9060/udp"
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "20000-20100:20000-20100/udp"
